import type { Metadata } from "next";
import {
  // Geist,
  // Geist_Mono
  Inter,
  Space_Grotesk,
} from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk", // Optional: for CSS custom property
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional: for CSS custom property
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} font-inter    antialiased`}
      >
        <div className="min-h-screen bg-white text-gray-900 landing">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
