import type { Metadata } from "next";
import {
  // Geist,
  // Geist_Mono
  Inter,
} from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthContextProvider } from "@/contexts/auth-context";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional: for CSS custom property
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <div className="min-h-screen bg-white text-gray-900 landing">
          <AuthContextProvider>{children}</AuthContextProvider>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
